Reason: updates to 0.5

diff --git a/main b/main
--- a/main
+++ b/main
@@ -1,8 +1,21 @@
 #!/bin/bash
-#PBS -l nodes=1:ppn=8,vmem=29gb,walltime=14:00:00
-#PBS -N trekker
+#PBS -l nodes=1:ppn=8,vmem=30gb,walltime=8:00:00
+#PBS -N app-trekker
 
-#set -e
-#set -x
+if [ ! -f csf_bin.nii.gz ]; then
+	time singularity exec -e docker://brainlife/mrtrix3:3.0.0 ./preprocess.sh
+fi
 
-time singularity exec -e docker://brainlife/trekker:0.4 ./run.sh
+time singularity exec -e docker://brainlife/trekker:0.5 ./tracking.py
+
+if [ ! -f ./track/track.tck ]; then
+	time singularity exec -e docker://brainlife/mrtrix3:3.0.0 ./convert.sh
+fi
+
+if [ -f ./track/track.tck ]; then
+	echo "complete"
+	exit 0
+else
+	echo "tracking failed"
+	exit 1
+fi
